repos:
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.13
-   repo: https://github.com/timothycrosley/isort
    rev: 6.0.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files", "--project", "module1"]
      types: [python]
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]